import Link from "next/link";
import { Fragment } from "react";
import AppLayout from "../../components/AppLayout";
import Head from 'next/head'

export default function Timeline( {userName} ) {
  return (
    <Fragment>
       <Head>
        <title>Devter❄️ | timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <AppLayout>
        <h1>This is the timeline of {userName}</h1>
        <Link href="/">
          <a>
            Go home
          </a>
        </Link>
      </AppLayout>

      <style jsx>{`
        h1{
          font-size: 36px;
          color: #09f;
        }
      `}</style>
    </Fragment>
  )
}


Timeline.getInitialProps = () => {
  return fetch('../api/hello.js')
  .then(res => res.json())
  .then(response => {
    const {userName} = response
    return userName
  })
  
}