import Head from 'next/head'
import Link from 'next/link'
import AppLayout from '../components/AppLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Devter❄️ | inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>

      <AppLayout>
        <h1>
          <a href='/'>devter</a>
        </h1>
        <nav className='timeline'>
          <Link href='/timeline'>
            <a>timeline</a>
          </Link>
        </nav>
      </AppLayout>
    
      <style jsx>
        {`
         h1{
           text-align: center;
           font-size: 48px;
         }
         nav{
            font-size: 24px;
            text-align: center;
         }
         a{
           color: #09f;
           text-decoration:none;
         }

         
       `}
      </style>
    </>
  )
}
